# Generated by Django 3.1.14 on 2022-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_auto_20220707_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='resolved_target',
            field=models.TextField(blank=True, null=True),
        ),
    ]
