# Generated by Django 3.1.14 on 2023-05-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_scan_resolved_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='policy_type',
            field=models.TextField(default='DEFAULT'),
        ),
    ]
