# Generated by Django 3.1.14 on 2023-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_scan_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='policy_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='policy_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
