# Generated by Django 3.1.14 on 2024-05-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0005_auto_20230516_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_scope',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
