# Generated by Django 3.1.14 on 2024-08-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0006_scan_scan_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='org_ref_id',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
