# Generated by Django 3.1.14 on 2025-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0007_scan_org_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
