version: "3.9"

networks:
  default:
    external: false
    name: nessus_secusyAPI

services:

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 8005:80
  #   volumes:
  #     - static_volume:/home/app/code/static
  #   depends_on:
  #     - nmapper-web
  #   restart: "on-failure"
  #   networks:
  #     - default

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - REDIS_URL=redis_db:6379
      #- ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=df7634#%4f
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6383:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - default

  nessus-db:
    image: mysql:5.7
    container_name: nessus-db
    ports:
      - 3301:3306
    environment:
       MYSQL_DATABASE: nessus_db
       MYSQL_ROOT_PASSWORD: test1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 1
    networks:
      - default
    volumes:
      - nessus_volume:/var/lib/mysql
      
  nessus-web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8005"
    volumes:
      - .:/code
    ports:
      - "8010:8005"
    depends_on:
      nessus-db:
          condition: service_healthy
    networks:
      - default

volumes:
  # static_volume:
  nessus_volume:
  redis_data:


  # consider refactoring this
  # redis:
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - secusy